language: java
before_install: ant init-ivy
script: ant all
jdk:
  - oraclejdk8
deploy:
  provider: releases
  api_key:
    secure: kVEBT2/0avk1seZeJMI9zTxP7Yrgz2IWa2WiHEgHWebDySMbC+3GAGCdoLC1RwAa5R18zh/D64uGuBzW6y79NDZh5ysnvcGul0rxNH9hppcXXixUY1c4OW7Even5fgEwaoZT5G+cSKJV05WrcFZTqVMs3eWOiYrYNiJ+9dMR6PE=
  file: dist/go-npm-poller.jar
  skip_cleanup: true
  on:
    repo: varchev/go-npm-poller
    tags: true
    all_branches: true
